### ISSUE TITLE
TestSuite

### ISSUE THREAD

**Issue by neico** [lua/lua#2]
Maybe it should be considered to include the [test suite](http://www.lua.org/tests/) with this repo to allow for CI tests like travis to run over it.

My fork for example builds the executeable and then does a simple test: `./lua -v -e "print( [[Successfully build Lua ($2)]] )" -e "os.exit( 0, true )"` where $2 refers to arch + config which results in a compile check with the following combinations:

- x86 Debug
- x86 DebugDLL
- x86 Release
- x86 ReleaseDLL
- x64 Debug
- x64 DebugDLL
- x64 Release
- x64 ReleaseDLL

I must admit though that the *DLL ones are disabled due to errors building luac on them.

Using the test suite would allow for more then just a compile check...
This could result in spotting more problems in the language that can then be reported back to the lua team

An alternative is to make a new repo with the test suite and then do some cross-repo compile & testing mumbo jumbo

**Comment by craigbarnes** [comment]
I took this `lua` account via a GitHub support request, after trying to contact the owner (who hadn't used it for 2 years). My intention was to act in good faith and to transfer it to the Lua team, should they ever want the account for something more official. At the moment, they don't seem interested in using it for anything, so I created this unofficial history of recent releases.

I don't really think it's appropriate to use it for development purposes. The Lua team already have their own development model and I don't want to give the impression this account/repo is somehow official.

I'll update the repo description to make it more clear.

**Comment by craigbarnes** [comment]
Although I like the suggestion of adding the test suite. I'll create a separate repo for that. I've also been meaning to write a script to import the full history of releases rather than just a few recent ones.

**Comment by craigbarnes** [comment]
Reopening this, just to remind myself to add the tests repo.

**Comment by craigbarnes** [comment]
The tests now live in the [lua/tests](https://github.com/lua/tests) repo.
