### ISSUE TITLE
5.3.1 patch. see http://www.lua.org/bugs.html#5.3.1

### ISSUE THREAD

**Issue by dailypips** [lua/lua#7]
patch liolib.c
see http://www.lua.org/bugs.html#5.3.1

**Comment by neico** [comment]
This will get fixed with the next official lua version, most likely 5.3.2

**Comment by craigbarnes** [comment]
No development or patching is done in this repo -- it's a git mirror of official *releases* only.

As @neico said, the patch will be included in the next version of Lua, which will be included here when it's released.
